../analyzebatch.pl \
../coapsims/ \
config=NRawSta,DataMode,TrafficInterval,BeaconInterval,Name,SimulationTime,TrafficType,TrafficIntervalDeviation,MaxTimeOfPacketsInQueue,NSta,CoolDownPeriod,NGroup,SlotFormat,NRawSlotCount,NRawSlotDuration,NRawSlotNum,TrafficString,Radius,numOfRpsElements \
stats=TotalTransmitTime,TotalReceiveTime,NumberOfSentPackets,NumberOfSuccessfulPackets,NumberOfDroppedPackets,AveragePacketSentReceiveTime,GoodputKbit,EDCAQueueLength,NumberOfSuccessfulRoundtripPackets,AveragePacketRoundTripTime,NumberOfCollisions,NumberOfMACTxMissedACKAndDroppedPacket,NumberOfBeaconsMissed,NumberOfTransmissionsCancelledDueToCrossingRAWBoundary,jitter,PacketLoss,InterPacketDelayAtServer,InterPacketDelayAtClient,InterPacketDelayDeviationPercentageAtServer,InterPacketDelayDeviationPercentageAtClient,Latency,EnergyRxIdle,EnergyTx \
$@
